add sonar-scanner cli and remove node cli soft link
huoyinghao/jenkins-agent pull request #9
Opened 2023-06-15 07:44 UTC by usernameisnull

- 添加了sonar-scanner的命令行，包括arm版本
- 移除了node的软链接，改为采用环境变量的方式

2023-06-16 03:37 UTC, muma378 requested changes

2023-06-16 03:37 UTC, muma378 commented on jenkins-agent/base/hack/install_utils.sh
> +  curl -fLo jdk-11.0.14.tar.gz https://aka.ms/download-jdk/microsoft-jdk-${JAVA_VERSION}-linux-x64.tar.gz
我们也不应该在base镜像里装jdk啊

2023-06-16 03:37 UTC, muma378 commented on jenkins-agent/nodejs/Dockerfile
> +ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH
这个问题虽然解决了，但是如果用户需要使用nvm install 其他的版本是不是又会出错呢

有2个相似的issue：https://github.com/nvm-sh/nvm/issues/2815 https://github.com/nvm-sh/nvm/issues/2164 似乎是由于安装和使用的用户不同（root和normal user）所致？

不使用nvm，用之前的方式安装会有什么问题来着?

2023-06-16 06:37 UTC, usernameisnull commented on jenkins-agent/nodejs/Dockerfile
> +ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH
改成了yum安装了

2023-06-16 06:51 UTC, usernameisnull commented on jenkins-agent/base/hack/install_utils.sh
> +  curl -fLo jdk-11.0.14.tar.gz https://aka.ms/download-jdk/microsoft-jdk-${JAVA_VERSION}-linux-x64.tar.gz
这个是后面的镜像都是在base镜像上再安装，避免重复安装

2023-06-16 07:36 UTC, muma378 commented on jenkins-agent/base/hack/install_utils.sh
> +  curl -fLo jdk-11.0.14.tar.gz https://aka.ms/download-jdk/microsoft-jdk-${JAVA_VERSION}-linux-x64.tar.gz
但是在go的构建镜像上要jdk干啥呢？不符合KISS的原则

到时候又会遇到基础镜像过大，需要精简话的问题

2023-06-19 01:54 UTC, usernameisnull commented on jenkins-agent/base/hack/install_utils.sh
> +  curl -fLo jdk-11.0.14.tar.gz https://aka.ms/download-jdk/microsoft-jdk-${JAVA_VERSION}-linux-x64.tar.gz
sonar-scanner需要

2023-06-19 03:06 UTC, muma378 commented on jenkins-agent/base/hack/install_utils.sh
> +  curl -fLo jdk-11.0.14.tar.gz https://aka.ms/download-jdk/microsoft-jdk-${JAVA_VERSION}-linux-x64.tar.gz
okk，看了下最早的版本确实镜像里有java sdk

2023-06-19 07:50 UTC, merged